-- Menggunakan INSERT OR REPLACE agar jika workzone sudah ada, datanya diupdate
INSERT OR REPLACE INTO workzone_details (workzone, sektor, korlap_username) VALUES 
('BLB', 'MLG 1', '@nicosuryanata @hndika @triyuni75 @Endrasakti'),
('KLJ', 'MLG 1', '@rolimartin @JackSpaaroww @firdausmulia @YantiMohadi'),
('SGS', 'MLG 2', '@iqbal_albana @merin97 @RizkyAHermawan @Choliz87 @agungspoetra'),
('PKS', 'MLG 2', '@iqbal_albana @merin97 @RizkyAHermawan @Choliz87 @agungspoetra'),
('LWG', 'MLG 2', '@iqbal_albana @merin97 @RizkyAHermawan @Choliz87 @agungspoetra'),
('TMP', 'MLG 2', '@iqbal_albana @merin97 @RizkyAHermawan @Choliz87 @agungspoetra'),
('SWJ', 'MLG 2', '@iqbal_albana @merin97 @RizkyAHermawan @Choliz87 @agungspoetra'),
('BRG', 'MLG 2', '@iqbal_albana @merin97 @RizkyAHermawan @Choliz87 @agungspoetra'),
('MLG', 'MLG 3', '@huliaiHzlq @RizkyMaulana_06 @Kikuch @anovitass'),
('GDG', 'MLG 3', '@azislutfi @anindya_putra @alibassss @bimalaksana90'),
('TUR', 'MLG 3', '@mochammadmulya @Penjozasmara @ipunklutfy @Gotam27'),
('GDI', 'MLG 3', '@mochammadmulya @Penjozasmara @ipunklutfy @Gotam27'),
('BNR', 'MLG 3', '@mochammadmulya @Penjozasmara @ipunklutfy @Gotam27'),
('DPT', 'MLG 3', '@mochammadmulya @Penjozasmara @ipunklutfy @Gotam27'),
('SBM', 'MLG 3', '@mochammadmulya @Penjozasmara @ipunklutfy @Gotam27'),
('APG', 'MLG 3', '@mochammadmulya @Penjozasmara @ipunklutfy @Gotam27'),
('KEP', 'MLG 3', '@azislutfi @anindya_putra @alibassss @bimalaksana90'),
('SBP', 'MLG 3', '@azislutfi @anindya_putra @alibassss @bimalaksana90'),
('GKW', 'MLG 3', '@azislutfi @anindya_putra @alibassss @bimalaksana90'),
('DNO', 'MLG 3', '@azislutfi @anindya_putra @alibassss @bimalaksana90'),
('PGK', 'MLG 3', '@azislutfi @anindya_putra @alibassss @bimalaksana90'),
('BTU', 'MLG 4', '@arishere @Flyco @aanksueb @diditdwif @athunk05'),
('NTG', 'MLG 4', '@arishere @Flyco @aanksueb @diditdwif @athunk05'),
('KPO', 'MLG 4', '@arishere @Flyco @aanksueb @diditdwif @athunk05');